"""'Add_enterprise_models'

Revision ID: b45a690ae260
Revises: 
Create Date: 2026-08-08 21:07:39.481370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b45a690ae260'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('chunking_strategy', sa.String(), nullable=False),
    sa.Column('regulations', sa.JSON(), nullable=False),
    sa.Column('drhp_count', sa.Integer(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_versions_id'), 'corpus_versions', ['id'], unique=False)
    op.create_table('historical_ipos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('issue_size_cr', sa.Float(), nullable=True),
    sa.Column('revenue_cr', sa.Float(), nullable=True),
    sa.Column('pat_cr', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('subscription_times', sa.Float(), nullable=True),
    sa.Column('listing_price', sa.Float(), nullable=True),
    sa.Column('listing_performance_pct', sa.Float(), nullable=True),
    sa.Column('promoters', sa.Text(), nullable=True),
    sa.Column('auditor', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('last_verified_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_ipos_company_name'), 'historical_ipos', ['company_name'], unique=False)
    op.create_index(op.f('ix_historical_ipos_id'), 'historical_ipos', ['id'], unique=False)
    op.create_index(op.f('ix_historical_ipos_sector'), 'historical_ipos', ['sector'], unique=False)
    op.create_table('regulation_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('regulation_id', sa.String(), nullable=False),
    sa.Column('version_tag', sa.String(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulation_versions_id'), 'regulation_versions', ['id'], unique=False)
    op.create_index(op.f('ix_regulation_versions_regulation_id'), 'regulation_versions', ['regulation_id'], unique=False)
    op.create_table('ai_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('tokens_prompt', sa.Float(), nullable=True),
    sa.Column('tokens_completion', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_executions_id'), 'ai_executions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_executions_workspace_id'), 'ai_executions', ['workspace_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('document_version', sa.String(), nullable=True),
    sa.Column('page_number', sa.String(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('regulation_id', sa.String(length=36), nullable=True),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulation_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_id'), 'evidence_records', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_records_workspace_id'), 'evidence_records', ['workspace_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_id'), 'review_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_review_decisions_workspace_id'), 'review_decisions', ['workspace_id'], unique=False)
    op.create_table('workflow_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('assigned_officer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_states_id'), 'workflow_states', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_states_workspace_id'), 'workflow_states', ['workspace_id'], unique=True)
    op.create_table('compliance_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('regulation', sa.String(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('regulation_version_id', sa.String(length=36), nullable=True),
    sa.Column('review_requirement', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_records.id'], ),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_findings_id'), 'compliance_findings', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_findings_rule_id'), 'compliance_findings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_compliance_findings_workspace_id'), 'compliance_findings', ['workspace_id'], unique=False)
    op.create_table('risk_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_records.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_findings_id'), 'risk_findings', ['id'], unique=False)
    op.create_index(op.f('ix_risk_findings_workspace_id'), 'risk_findings', ['workspace_id'], unique=False)
    op.drop_index('ix_drhp_sections_id', table_name='drhp_sections')
    op.drop_index('ix_drhp_sections_section_key', table_name='drhp_sections')
    op.drop_index('ix_drhp_sections_workspace_id', table_name='drhp_sections')
    op.drop_table('drhp_sections')
    op.drop_index('ix_drhp_section_versions_id', table_name='drhp_section_versions')
    op.drop_index('ix_drhp_section_versions_section_id', table_name='drhp_section_versions')
    op.drop_index('ix_drhp_section_versions_workspace_id', table_name='drhp_section_versions')
    op.drop_table('drhp_section_versions')
    op.drop_index('ix_drhp_comments_id', table_name='drhp_comments')
    op.drop_index('ix_drhp_comments_section_id', table_name='drhp_comments')
    op.drop_index('ix_drhp_comments_workspace_id', table_name='drhp_comments')
    op.drop_table('drhp_comments')
    op.add_column('audit_events', sa.Column('role', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('previous_state', sa.Text(), nullable=True))
    op.add_column('audit_events', sa.Column('new_state', sa.Text(), nullable=True))
    op.add_column('audit_events', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('audit_events', sa.Column('evidence_id', sa.String(length=36), nullable=True))
    op.add_column('audit_events', sa.Column('ai_model', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('prompt_version', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('regulation_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_events', 'regulation_version')
    op.drop_column('audit_events', 'prompt_version')
    op.drop_column('audit_events', 'ai_model')
    op.drop_column('audit_events', 'evidence_id')
    op.drop_column('audit_events', 'reason')
    op.drop_column('audit_events', 'new_state')
    op.drop_column('audit_events', 'previous_state')
    op.drop_column('audit_events', 'role')
    op.create_table('drhp_comments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('section_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('comment_text', sa.TEXT(), nullable=False),
    sa.Column('resolved', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['drhp_sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drhp_comments_workspace_id', 'drhp_comments', ['workspace_id'], unique=False)
    op.create_index('ix_drhp_comments_section_id', 'drhp_comments', ['section_id'], unique=False)
    op.create_index('ix_drhp_comments_id', 'drhp_comments', ['id'], unique=False)
    op.create_table('drhp_section_versions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('section_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('data_json', sqlite.JSON(), nullable=True),
    sa.Column('change_summary', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['drhp_sections.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drhp_section_versions_workspace_id', 'drhp_section_versions', ['workspace_id'], unique=False)
    op.create_index('ix_drhp_section_versions_section_id', 'drhp_section_versions', ['section_id'], unique=False)
    op.create_index('ix_drhp_section_versions_id', 'drhp_section_versions', ['id'], unique=False)
    op.create_table('drhp_sections',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('section_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('section_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('data_json', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('compliance_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('compliance_findings', sqlite.JSON(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drhp_sections_workspace_id', 'drhp_sections', ['workspace_id'], unique=False)
    op.create_index('ix_drhp_sections_section_key', 'drhp_sections', ['section_key'], unique=False)
    op.create_index('ix_drhp_sections_id', 'drhp_sections', ['id'], unique=False)
    op.drop_index(op.f('ix_risk_findings_workspace_id'), table_name='risk_findings')
    op.drop_index(op.f('ix_risk_findings_id'), table_name='risk_findings')
    op.drop_table('risk_findings')
    op.drop_index(op.f('ix_compliance_findings_workspace_id'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_rule_id'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_id'), table_name='compliance_findings')
    op.drop_table('compliance_findings')
    op.drop_index(op.f('ix_workflow_states_workspace_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    op.drop_index(op.f('ix_review_decisions_workspace_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_evidence_records_workspace_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_ai_executions_workspace_id'), table_name='ai_executions')
    op.drop_index(op.f('ix_ai_executions_id'), table_name='ai_executions')
    op.drop_table('ai_executions')
    op.drop_index(op.f('ix_regulation_versions_regulation_id'), table_name='regulation_versions')
    op.drop_index(op.f('ix_regulation_versions_id'), table_name='regulation_versions')
    op.drop_table('regulation_versions')
    op.drop_index(op.f('ix_historical_ipos_sector'), table_name='historical_ipos')
    op.drop_index(op.f('ix_historical_ipos_id'), table_name='historical_ipos')
    op.drop_index(op.f('ix_historical_ipos_company_name'), table_name='historical_ipos')
    op.drop_table('historical_ipos')
    op.drop_index(op.f('ix_corpus_versions_id'), table_name='corpus_versions')
    op.drop_table('corpus_versions')
    # ### end Alembic commands ###
